# Serve static assets directly (no redirect)
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = false

# Serve JavaScript files directly
[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200
  force = false

# Serve CSS files directly
[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200
  force = false

# Serve other assets directly
[[redirects]]
  from = "/*.json"
  to = "/:splat.json"
  status = 200
  force = false

[[redirects]]
  from = "/*.ico"
  to = "/:splat.ico"
  status = 200
  force = false

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200
  force = false

# MSW service worker
[[redirects]]
  from = "/mockServiceWorker.js"
  to = "/mockServiceWorker.js"
  status = 200
  force = false

# SPA fallback - MUST be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/mockServiceWorker.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Service-Worker-Allowed = "/"
    Cache-Control = "no-cache, no-store, must-revalidate"